### ISSUE TITLE
Test cases for `FileNVM` are unstable

### ISSUE THREAD

**Issue by shinnya** [frugalos/cannyls#15]
Stochastically test cases for `FileNVM` fail.

## How to re-produce

Just run `cargo test` many times and you'll get errors like the following:

```console
failures:

---- nvm::file::tests::create_if_absent_works stdout ----
Error: Other (cause; Resource temporarily unavailable (os error 11))
HISTORY:
  [0] at src/nvm/file.rs:80
  [1] at src/nvm/file.rs:183
  [2] at src/nvm/file.rs:422

thread 'nvm::file::tests::create_if_absent_works' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', libtest/lib.rs:337:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    nvm::file::tests::create_if_absent_works

test result: FAILED. 58 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by yuezato** [comment]
Note: To reproduce this, it may requires to do test with multithreads (i.e., RUST_TEST_THREADS >= 2).

**Comment by yuezato** [comment]
↑ My previous comment is flaw.
We've repaired this issue in this PR https://github.com/frugalos/cannyls/pull/20.
